
services:
  client:
    container_name: client
    image: niritz/truegas-client
    hostname: truegasdocker-client
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm start
