version: '3.8'

services:
  client:
    container_name: client
    image: niritz/truegas-client
    hostname: truegasdocker-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app