version: '3.8'

services:
  client:
    container_name: client
    image: niritz/truegas-client
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
